Repository InnoWebLabs/Vehigo, pull requests merged in 2025-10, with the labels that each got.

#824 Redesigned the Blogs pages
  assets/css/blog-enhanced.css
  assets/css/blog-post.css
  blog.html
  blogs/blog1.html
  blogs/blog2.html
  blogs/blog3.html
  blogs/blog4.html
  blogs/blog5.html
Labels: level 2, gssoc25

#840 Fix Footer alignment of pricing.html page
  src/pages/pricing.html
Labels: level 1, gssoc25

#843 🔒♿🚀 Security, Accessibility & Performance Improvements
  .vscode/settings.json
  SECURITY_IMPROVEMENTS.md
  assets/css/accessibility-improvements.css
  index.html
Labels: level 3, gssoc25

#850 [Bug Fix] Fixed inverted theme toggler labels
  ContactUs.html
Labels: level 1, gssoc25

#851 Improve Contact Form Validation and Accessibility
  ContactUs.css
  ContactUs.html
  ContactUs.js
Labels: level 2, gssoc25

#867 Made Header Links Visible in Light Mode
  sitemap.html
Labels: level 1, gssoc25

#857 changed redirect error in homapage
  index.html
Labels: level 2, gssoc25

#871 Changed the phonenumber field to tel
  src/pages/login.html
Labels: level 1, gssoc25

#873 Update Rent Car page footer social links to company profiles #866
  rentcar.html
Labels: level 1, gssoc25

#889 Footer social links on Askaques page redirect to company profiles (#877)
  blog.html
  src/pages/Askaques.html
Labels: level 1, gssoc25

#894 Fixed About Us page
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#907 redesign Add Your Vehicle form
  rentcar.html
Labels: level 1, gssoc25

#905 Added Search Bar to Offline Centers Page
  offline.html
Labels: level 2, gssoc25

#896 feat(tandc): unify T&C footer with home; correct Ask page T&C link; u…
  ISSUE.md
  PULL_REQUEST.md
  src/pages/Askaques.html
  src/pages/tandc.html
  tandc.html
Labels: level 1, gssoc25

#898 make working of chatbot
  index.html
Labels: level 3, gssoc25

#908 minor-layout-fixes
  index.html
Labels: level 1, gssoc25

#914 Update footer of pricing section for light theme , Checked footer lin…
  package-lock.json
  package.json
  src/assets/styles/loginstyle.css
  src/pages/pricing.html
Labels: level 2, gssoc25

#915 Fixed the Index Page
  src/assets/styles/style.css
  src/index.html
Labels: level 2, gssoc25
