Repository InnoWebLabs/Vehigo, pull requests merged in 2025-09, with the labels that each got.

#508 Fixed Login Page
  src/assets/styles/loginstyle.css
  src/pages/login.html
Labels: level 2, gssoc25

#516 added header in help centre
  offline.html
  src/pages/help-center.html
Labels: level 2, gssoc25

#520 added login button in help centre page
  src/pages/help-center.html
Labels: level 3, gssoc25

#527 Align and Standardize Header Layout on Main Page (Dark & Light Mode Support)
  assets/css/style.css
  index.html
Labels: level 2, gssoc25

#525 Enhancement: Added Forgot Password Option with Validation
  src/assets/styles/loginstyle.css
  src/pages/forgot-password.html
Labels: level 2, gssoc25

#533 Pricing plan redirect correctly in fare calculator section
  src/pages/Askaques.html
  src/pages/bill.html
Labels: level 3, gssoc25

#566 Redesign the blog pages with new effetcs and styling
  assets/css/blog-enhanced.css
  assets/css/blog-post.css
  assets/js/blog-enhanced.js
  blog-page-dark-mode.png
  blog-page-fixed.png
  blog.html
  blogs/blog1.html
  blogs/blog2.html
  blogs/blog3.html
  blogs/blog4.html
  blogs/blog5.html
  src/blog.css
Labels: level 2, gssoc25

#564 Fixed Home page Hover bug
  src/index.html
Labels: level 2, gssoc25

#558 Fixed the broken page on pricing
  assets/styles/pricing-help.css
  src/pages/pricing.html
Labels: bug, level 2, gssoc25

#557 Indexpage UI enhacement
  index.html
Labels: level 2, gssoc25

#579 Feat: Added confirm password field
  src/pages/login.html
Labels: level 2, gssoc25

#594 Login Button now navigating to Login/Signup Page
  index.html
Labels: level 1, gssoc25

#597 Improve footer visibility in light mode for better readability
  index.html
Labels: level 2, gssoc25

#576 Updated About Page Navbar for Consistency
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#627 fix: add responsive padding to homepage container (#622)
  index.html
Labels: level 2, gssoc25

#623 Revamp Blog Page UI and Implement Dark/Light Theme with Navigation
  index.html
Labels: level 2, gssoc25

#629 Fixed About us page navbar
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#659 Fix/pricing header and tabs
  blog.html
  src/pages/pricing.html
Labels: level 2, gssoc25

#657 Updated About Us Page Header to Match Home Screen Design
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#650 ISSUE #639
  privacypolicy.html
Labels: level 2, gssoc25

#649 ISSUE #641
  ContactUs.html
Labels: level 2, gssoc25

#668 Change font colour of text which is not visible in light mode
  index.html
Labels: level 2, gssoc25

#670 changed header of privacy policy
  privacypolicy.html
Labels: level 2, gssoc25

#690 fix: resolve Explore cars navigation issues across all pages Fixes #688
  ContactUs.html
  buy.html
  featured-car.html
  index.html
  offline.html
  src/pages/about.html
  src/pages/login.html
Labels: level 3, gssoc25

#707 changed ui of rent your car page
  rentcar.html
  scripts/rentcar.js
Labels: level 2, gssoc25

#700 Fixed Navbar Navigation from About Us Screen
  src/pages/about.html
Labels: level 3, gssoc25

#740 Added header and darkmode
  sitemap.html
Labels: level 2, gssoc25

#739 Fix dark mode visibility issues issue #738
  index.html
Labels: level 3, gssoc25

#790 Changed the footer layout in Ask a Question page
  src/pages/Askaques.html
Labels: level 2, gssoc25

#787 Fix footer quick links in help-center.html
  src/pages/help-center.html
Labels: level 3, gssoc25

#793 Made the blog.html link working in bill.html
  src/pages/bill.html
Labels: level 2, gssoc25

#792 Enhance About Us Page – Fix Card Alignment, Add Contributors Section, and UI Refinements (#710)
  src/assets/styles/about-animations.css
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#819 added dropdown in index at location
  index.html
Labels: level 2, gssoc25, frontend

#821 Made the header visible and implemented dark mode in Offline Centres page
  offline.html
Labels: level 2, gssoc25

#823 Fix the text visibility on Cars Cards
  assets/css/dark.css
Labels: level 2, gssoc25
