Repository InnoWebLabs/Vehigo, pull requests merged in 2025-07, with the labels that each got.

#86 Solved issue #75 -added company logo as favicon
  index.html
Labels: level 1, gssoc25

#95 Ask a question page added
  index.html
  src/pages/Askaques.html
Labels: level 1, gssoc25

#157 fix(CSS): Correct footer column alignment-126
  assets/css/style.css
Labels: level 2, gssoc25

#154 Fixed signup/login page issue
  ContactUs.html
  assets/css/dark.css
  assets/css/style.css
  assets/js/script.js
  index.html
  login.html
  offline.html
  privacypolicy.html
  rentcar.html
  signup.html
Labels: level 2, gssoc25

#164 Solved Issue #143-Navandfoot offline
  index.html
  offline.html
  src/pages/about.html
Labels: level 1, gssoc25

#167 Added nav-bar to the about us page and enahnced texts in the meet our team section of that page
  about-us.html
  blog.html
  featured-car.html
  rentcar.html
  src/pages/about.html
Labels: level 1, gssoc25

#171 Added Form Validation Feedback on Homepage Search
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: level 2, gssoc25

#178 Added filtering and sorting in the UI
  src/index.html
Labels: level 2, gssoc25

#187 Fix: Added Missing Global Navbar to About Page
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 1, gssoc25

#193 added supabase for dynamic fetching of details
  src/index.html
Labels: level 3, gssoc25

#192 Solved Issue #165 -added map and offline centres in offline centres page
  offline.html
Labels: level 2, gssoc25
