Repository InnoWebLabs/Vehigo, pull requests merged in 2025-08, with the labels that each got.

#216 Fixed : Fixed Dark mode button not working, not switching and not showing dark mode in features-car.html
  CONTRIBUTING.md
  README.md
  assets/css/buy.css
  buy.html
  buycar.js
  featured-car.html
  index.html
Labels: level 2, gssoc25

#221 ENHANCE : Improve footer UX by disabling logo animation and linking social icons
  assets/css/style.css
  index.html
Labels: level 1, gssoc25

#218 Improved: feedback form with proper css and functional components
  .vscode/launch.json
  assets/css/feebackForm.css
  featured-car.html
  feedbackForm.html
Labels: level 2, gssoc25

#219 fix: Correct theme toggle visibility and alignment in dark mode
  assets/css/style.css
  index.html
Labels: level 2, gssoc25

#235 Fixed Signup Container overflowing
  signup.html
Labels: level 1, gssoc25

#233 Update SignUp Page Feature
  login.html
  signup.html
  src/pages/login.html
  styles/loginstyle.css
Labels: level 2, gssoc25

#232 Fixed hover effect of "rent now"
  README.md
  buy.html
  buyscar.css
  index.html
  login.html
Labels: level 1, gssoc25

#253 login-feature-enhanced with option and toggle mode + .js file
  login.html
Labels: level 3, gssoc25

#249 Fixed non working-links of Navbar in ContactUS Page
  ContactUs.html
Labels: level 1, gssoc25

#247 Fixed Rentcar page Bug & Fixed Nav-bar and Content Overflowing Bug
  ContactUs.css
  ContactUs.html
  rentcar.html
  styles/rentcar.css
Labels: level 3, gssoc25

#275 adding github icon
  ContactUs.html
  assets/css/style.css
  git1.png
  git2.png
  offline.html
  src/assets/styles/style.css
  src/index.html
  src/pages/about.html
  src/pages/accountpage.html
  src/pages/bill.html
  src/pages/carPage.html
  src/pages/trackPage.html
  styles/mainStyle.css
Labels: level 1, gssoc25

#270 Missing logo
  .DS_Store
  ContactUs.html
  SelectionPage.html
  accountpage.html
  blog.html
  buy.html
  carPage.html
  featured-car.html
  feedbackForm.html
  hostPage.html
  index.html
  login.html
  offline.html
  registrationPage.html
  rentcar.html
  sell.html
  signup.html
  tandc.html
  trackPage.html
Labels: level 1, gssoc25

#269 Fixed the Links in T&C page and Footer Sections of Home page
  src/index.html
  tandc.html
Labels: level 2, gssoc25

#265 Fixed Navbar Links of offline.html
  offline.html
Labels: level 1, gssoc25

#264 ENHANCE : sign in and sign up page ui/ux
  login.html
  signup.html
Labels: level 3, gssoc25

#291 Added NavBar and Fixed Bugs in Askaques Page
  src/pages/Askaques.html
Labels: level 1, gssoc25

#283 Update login and signup pages UI
  blogs/blog4.html
  login.html
  signup.html
Labels: level 2, gssoc25

#310 added about us page with the nice ui design
  src/index.html
  src/pages/about.html
Labels: level 3, gssoc25

#301 Fixed NavBar of Contact us Page
  ContactUs.css
  ContactUs.html
Labels: level 1, gssoc25

#300 Fixed NavBar UI and Switch Theme Button
  assets/css/dark.css
  offline.html
  styles/offline.css
Labels: level 1, gssoc25

#299 Fixed Testimonials Section of About Page
  src/assets/styles/about.css
  src/assets/styles/style.css
  src/pages/about.html
Labels: level 1, gssoc25

#318 Improve Hero Section Padding for Better Readability
  index.html
  src/index.html
  src/pages/about.html
Labels: level 2, gssoc25

#317 Fix: Center align Google Sign-in button
  login.html
  signup.html
Labels: level 1, gssoc25

#312 Add comprehensive sell car functionality and improved login validation
  buy.html
  login.html
  sell.html
  signup.html
Labels: level 3, gssoc25

#336 fixed issue #332 -fixed UI of home page to some extent
  index.html
Labels: level 3, gssoc25

#334 Fixed Bug and Navbar of About Us
  src/pages/about.html
Labels: level 2, gssoc25

#342 Fixed Filter section of Home page
  src/assets/styles/style.css
  src/index.html
Labels: level 1, gssoc25

#338 Fix: Update 'Rent now' buttons to redirect to rent your car button and remove extra things from offline.html
  index.html
  offline.html
Labels: level 2, gssoc25

#343 Fix Footer of Offline-center page
  assets/css/style.css
  offline.html
Labels: level 1, gssoc25

#348 Fixed Footer section of Home Page
  src/assets/styles/style.css
  src/index.html
Labels: level 1, gssoc25

#344 Update Contact Form
  ContactUs.html
Labels: level 1, gssoc25

#355 Search option on home page and buy now is fixed.
  buy.html
  buycar.js
  buyscar.css
Labels: level 1, gssoc25

#381 Added a update profile controller
  vehigo-backend/src/controllers/authController.js
Labels: level 3, gssoc25

#380 Navigation Enhancement/improvement.
  accountpage.html
  index.html
  src/index.html
  src/pages/about.html
  src/pages/accountpage.html
  src/pages/bill.html
Labels: level 2, gssoc25

#376 feat: enable smooth scroll-to-top on logo click in src/index.html
  src/index.html
Labels: level 1, gssoc25

#374 Fix : Offline center page cards to be visible on theme toggle
  offline.html
Labels: level 1, gssoc25

#370 Added dynamic year functionality to footer on HTML pages
  ContactUs.html
  accountpage.html
  carPage.html
  privacypolicy.html
  src/index.html
  src/pages/accountpage.html
  src/pages/bill.html
  src/pages/carPage.html
  src/pages/trackPage.html
  trackPage.html
  vehigo-backend/accountpage.html
Labels: level 1, gssoc25

#401 Fixed carPage
  carPage.html
  src/assets/styles/carPage.css
Labels: level 1, gssoc25

#398 Fixed Navbar Bug in About page
  src/pages/about.html
Labels: level 1, gssoc25

#397 Fixed Misaligned Header and Content on featured-car.html
  assets/css/style.css
  buy.html
  featured-car.html
  index.html
Labels: level 2, gssoc25

#390 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: level 3, gssoc25

#412 fix route
  src/pages/login.html
Labels: level 1, gssoc25

#416 Fixed Misaligned About Us Header & Dark Theme Support
  src/assets/styles/about.css
  src/pages/about.html
  src/pages/login.html
Labels: level 2, gssoc25

#434 Enhance Rent Car Page – Header & Content Improvements
  rentcar.html
  styles/rentcar-modern.css
Labels: level 2, gssoc25

#431 Pre-loader + AOS animations
  ContactUs.html
  blog.html
  hostPage.html
  index.html
  offline.html
  preloader.css
  preloader.js
  rentcar.html
  src/pages/about.html
Labels: level 3, gssoc25

#430 Fixed About Us Page UI & Add Content
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#425 Fixed Non-working Links of Login page
  src/pages/login.html
Labels: level 1, gssoc25

#424 Updated README and added GSSOC logo
  README.md
  assets/images/gssoc logo.png
Labels: level 2, gssoc25

#423 Fixed uneven spacing between Offline Centers boxes/cards
  offline.html
  src/assets/styles/about.css
  styles/offline.css
Labels: level 2, gssoc25

#456 Fixed Sidebar Layout & Background Color
  assets/css/style.css
  offline.html
Labels: level 2, gssoc25

#475 solved issue #449- fixed issue with footer of about us page
  index.html
  src/pages/about.html
Labels: level 2, gssoc25

#466 [ENHANCE]: the alignment issue of about page is resolved
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#462 [ENHANCE]: decrease the speed of animation
  assets/css/style.css
Labels: level 2, gssoc25

#476 Make Footer of Offline Centers Page Consistent with Other Screens
  assets/css/style.css
  offline.html
Labels: level 2, gssoc25

#479 Fix Blog Screen Layout, Add Transitions & Favicon
  assets/css/style.css
  blogs/blog1.html
  blogs/blog2.html
  blogs/blog3.html
  blogs/blog4.html
  blogs/blog5.html
  src/pages/bill.html
Labels: level 2, gssoc25

#486 UI Improvements: Added Welcome Message, Enhanced Form Visibility, and Favicon
  src/assets/styles/loginstyle.css
  src/pages/login.html
Labels: level 2, gssoc25

#487 Enhnaced the Ui/UX of the CarPage
  .env.local
  carPage.html
  controllers/auth.controller.js
  node_modules/.package-lock.json
  node_modules/nodemailer/.gitattributes
  node_modules/nodemailer/.ncurc.js
  node_modules/nodemailer/.prettierrc.js
  node_modules/nodemailer/CHANGELOG.md
  node_modules/nodemailer/CODE_OF_CONDUCT.md
  node_modules/nodemailer/LICENSE
  node_modules/nodemailer/README.md
  node_modules/nodemailer/SECURITY.txt
  node_modules/nodemailer/lib/addressparser/index.js
  node_modules/nodemailer/lib/base64/index.js
  node_modules/nodemailer/lib/dkim/index.js
  node_modules/nodemailer/lib/dkim/message-parser.js
  node_modules/nodemailer/lib/dkim/relaxed-body.js
  node_modules/nodemailer/lib/dkim/sign.js
  node_modules/nodemailer/lib/fetch/cookies.js
  node_modules/nodemailer/lib/fetch/index.js
  node_modules/nodemailer/lib/json-transport/index.js
  node_modules/nodemailer/lib/mail-composer/index.js
  node_modules/nodemailer/lib/mailer/index.js
  node_modules/nodemailer/lib/mailer/mail-message.js
  node_modules/nodemailer/lib/mime-funcs/index.js
  node_modules/nodemailer/lib/mime-funcs/mime-types.js
  node_modules/nodemailer/lib/mime-node/index.js
  node_modules/nodemailer/lib/mime-node/last-newline.js
  node_modules/nodemailer/lib/mime-node/le-unix.js
  node_modules/nodemailer/lib/mime-node/le-windows.js
  node_modules/nodemailer/lib/nodemailer.js
  node_modules/nodemailer/lib/punycode/index.js
  node_modules/nodemailer/lib/qp/index.js
  node_modules/nodemailer/lib/sendmail-transport/index.js
  node_modules/nodemailer/lib/ses-transport/index.js
  node_modules/nodemailer/lib/shared/index.js
  node_modules/nodemailer/lib/smtp-connection/data-stream.js
  node_modules/nodemailer/lib/smtp-connection/http-proxy-client.js
  node_modules/nodemailer/lib/smtp-connection/index.js
  node_modules/nodemailer/lib/smtp-pool/index.js
  node_modules/nodemailer/lib/smtp-pool/pool-resource.js
  node_modules/nodemailer/lib/smtp-transport/index.js
  node_modules/nodemailer/lib/stream-transport/index.js
  node_modules/nodemailer/lib/well-known/index.js
  node_modules/nodemailer/lib/well-known/services.json
  node_modules/nodemailer/lib/xoauth2/index.js
  node_modules/nodemailer/package.json
  package-lock.json
  package.json
  vehigo-backend/src/config/db.js
Labels: level 2, gssoc25

#500 Fixed About Us Page Header & Sidebar Visibility
  src/assets/styles/about.css
  src/pages/about.html
Labels: level 2, gssoc25

#499 added custom 404 page
  404.html
  assets/images/404.gif
  middlewares/isAuthenticated.middleware.js
  routes/auth.routes.js
  server.js
Labels: level 2, gssoc25

#494 Enhance blog styles with transitions and hover effects
  src/blog.css
Labels: level 2, gssoc25

#490 Added Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/Pull_request_template.md
Labels: level 2, gssoc25
